name: Catalyst
favicon: null
layout_spectrum: 1
typography_spectrum: 0.14222
title: Catalyst Art Show
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3a3934'
    - '#ffffff'
    - '#da7c57'
    - '#654e43'
    - '#b4654b'
  brandStrength: 0.10619344934821129
  lightness: 0.3469585820566863
  saturation: 0.9263628791086376
  rhythmicContrast: 0.49281897535547614
purpose: []
