name: Catalyst
favicon: null
layout_spectrum: 0
typography_spectrum: 0.14222
title: Claw Machining
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#fedb5e'
    - '#fd7754'
    - '#5f5f5f'
    - '#9a9a9a'
  brandStrength: 0
  lightness: 0.5625
  saturation: 0.9263628791086376
  rhythmicContrast: 0.75
purpose: []
