name: Catalyst
favicon: null
layout_spectrum: 0.567512515000999
typography_spectrum: 0.042201872216537595
title: Catalyst Art Show
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.10619344934821129
  lightness: 0.3469585820566863
  saturation: 0.9263628791086376
  rhythmicContrast: 0.49281897535547614
purpose: []
